name: CI/CD

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Docker
          uses: alxndrbauer/php-ci-action@master
        - name: dependencies
          run: |
            composer --version
            ls -la
