name: CI/CD

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  composer-dependencies:
    runs-on: ubuntu-latest
    container: 'hfhit/php-ci:php-73'
    steps:
        - uses: actions/checkout@v1
        - name: dependencies
          run: |
            ls -la
            whoami
            id $(whoami)
            su root
            composer install
            
  node-dependencies:
    runs-on: ubuntu-latest
    container: 'hfhit/php-ci:php-73'
    steps:
        - uses: actions/checkout@v1
        - name: dependencies
          run: |
            yarn install   

              
  test-approve:
    runs-on: ubuntu-latest
    container: 'hfhit/php-ci:php-73'
    steps:
        - uses: actions/checkout@v1
        - name: test-test
          run: |
            ls -la
