name: CI/CD

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  composer-dependencies:
    runs-on: ubuntu-latest
    container: 'hfhit/php-ci:latest'
    steps:
        - uses: actions/checkout@v1
        - name: dependencies
          run: |
            ls -la
            composer install
            
  node-dependencies:
    runs-on: ubuntu-latest
    container: 'hfhit/php-ci:latest'
    steps:
        - uses: actions/checkout@v1
        - name: dependencies
          run: |
            yarn install            
